In [1]:
# Importing necessary libraries
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
import matplotlib
matplotlib.rcParams["figure.figsize"] = (20, 10)

import seaborn as sns
from collections import Counter
from sklearn.metrics import classification_report, confusion_matrix
import joblib

## Reading full data and cleaning data eg. aligning and adding separators
after loading the data it was clear that it was not aligned well. so i used separators to make the data very well aligned for easy reading and cleaning.

In [2]:
data = pd.read_csv("Data/bank-full.csv")
data.head()

  age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
0  58;"management";"married";"tertiary";"no";2143...
1  44;"technician";"single";"secondary";"no";29;"...
2  33;"entrepreneur";"married";"secondary";"no";2...
3  47;"blue-collar";"married";"unknown";"no";1506...
4  33;"unknown";"single";"unknown";"no";1;"no";"n...

In [3]:
law = pd.read_csv("Data/bank-full.csv", sep=";")
law.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

## Loading, aligning and Cleaning Data
after aligning teh data, i started cleaning the data.
checking for nulls values, knowing the shape, dropping some columns and understanding the data
Clearing outliers, encoding and feature extraction

In [4]:
law.shape

(45211, 17)

In [5]:
law_new = law.drop(["default", "contact", "poutcome"], axis = "columns")
law_new.head()

,age,job,marital,education,balance,housing,loan,day,month,duration,campaign,pdays,previous,y
0,58,management,married,tertiary,2143,yes,no,5,may,261,1,-1,0,no
1,44,technician,single,secondary,29,yes,no,5,may,151,1,-1,0,no
2,33,entrepreneur,married,secondary,2,yes,yes,5,may,76,1,-1,0,no
3,47,blue-collar,married,unknown,1506,yes,no,5,may,92,1,-1,0,no
4,33,unknown,single,unknown,1,no,no,5,may,198,1,-1,0,no

In [6]:
law_new.shape

(45211, 14)

In [7]:
law_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   balance    45211 non-null  int64
 5   housing    45211 non-null  object
 6   loan       45211 non-null  object
 7   day        45211 non-null  int64
 8   month      45211 non-null  object
 9   duration   45211 non-null  int64
 10  campaign   45211 non-null  int64
 11  pdays      45211 non-null  int64
 12  previous   45211 non-null  int64
 13  y          45211 non-null  object
dtypes: int64(7), object(7)
memory usage: 4.8+ MB

In [8]:
law_new.isnull().sum()

age          0
job          0
marital      0
education    0
balance      0
housing      0
loan         0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
y            0
dtype: int64

In [9]:
law_new.describe()

,age,balance,day,duration,campaign,pdays,previous
count,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000
mean,40.936210,1362.272058,15.806419,258.163080,2.763841,40.197828,0.580323
std,10.618762,3044.765829,8.322476,257.527812,3.098021,100.128746,2.303441
min,18.000000,-8019.000000,1.000000,0.000000,1.000000,-1.000000,0.000000
25%,33.000000,72.000000,8.000000,103.000000,1.000000,-1.000000,0.000000
50%,39.000000,448.000000,16.000000,180.000000,2.000000,-1.000000,0.000000
75%,48.000000,1428.000000,21.000000,319.000000,3.000000,-1.000000,0.000000
max,95.000000,102127.000000,31.000000,4918.000000,63.000000,871.000000,275.000000

## Feature Engineering (Outlier Dection and One hot Encoding)
#### Dealing with outliers using percentile in balance
Clearing everything below 0.999 and below 0.001 quantile.

In [ ]:
max, min = law_new.balance.quantile([0.001, 0.999])
max, min

In [509]:
max = law_new.balance.quantile(0.999)

In [ ]:
law_new[law_new.balance > max]

In [511]:
min = law_new.balance.quantile(0.001)

In [ ]:
law_new[law_new.balance < min]

In [ ]:
## Keeping everything below the maximun quantile and everything above my minimum quantile 
law_new2 = law_new[(law_new.balance < max)  & (law_new.balance > min)]
law_new2.shape

In [ ]:
law_new2["y"].value_counts(normalize = True)

# Encoding / One Hot encoding

In [ ]:
month_to_nv = {
    "jan": 1,
    "feb": 2,
    "mar": 3,
    "apr": 4,
    "may": 5,
    "jun": 6,
    "jul": 7,
    "aug": 8,
    "sep": 9,
    "oct": 10,
    "nov": 11,
    "dec": 12
}

for df in [law_new2]:
    if "month" in df.columns and df["month"].dtype == "object":
        df["month"] = df["month"].map(month_to_nv)

In [ ]:
law_new2.head(5)

In [ ]:
# Changing Yes and No to 1 and 0 respectively (Where Yes is 1 and No is 0)
yes_no_columns = law_new2.columns[law_new2.isin(["yes", "no"]).any()]
law_new2[yes_no_columns] = law_new2[yes_no_columns].applymap(lambda x: 1 if x == "yes" else (0 if x == "no" else x))

In [ ]:
law_new2.head()

In [ ]:
print(law_new2.dtypes)

In [ ]:
P_values = ["age", "housing", "loan", "day", "month", "duration", "campaign", "previous"]
plt.figure(figsize=(15, 20))
for i, P_values in enumerate(P_values):
    plt.subplot(5, 2, i + 1)
    if law_new2[P_values].dtype == "object":
        sns.stripplot(x = P_values, y="y", data = law_new2, jitter=True, alpha=0.6)
    else:
        plt.scatter(law_new2[P_values], law_new2["y"], alpha = 0.5, color = "red")
        plt.xlabel(P_values)
        plt.ylabel("y")
        plt.title(f"{P_values} vs y")

plt.tight_layout()
plt.show()

Encoding Columns

In [548]:
cols_to_encode = ["education", "marital", "job"]
dummies = pd.get_dummies(law_new2[cols_to_encode], dtype=int)

In [549]:
law_new2_rest = law_new2.drop(columns=cols_to_encode)

In [550]:
law_new3 = pd.concat([law_new2_rest, dummies], axis=1)

In [ ]:
law_new3.head()

In [ ]:
print(law_new3.dtypes)

In [ ]:
law_new3.shape

In [555]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [ ]:
X = law_new3.drop("y", axis ="columns")
X.head()

In [ ]:
y = law_new3.y
y.head()

In [573]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 10)

In [ ]:
model = LogisticRegression()
model.fit(X_train, y_train)
model.score(X_test, y_test)

In [ ]:
model.predict(X_test,)

In [ ]:
y_test

In [ ]:

y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))
print("\n", Counter(y_test), "\n", Counter(y_pred))

In [ ]:
joblib.dump(model, "model.pkl")